language: ruby
rvm:
  - 1.9.3
services:
  - redis
env:
  - ANALYTICS_ID=UA-33980823-1
  - OAUTH_USER_ID=603467509357.apps.googleusercontent.com
  - OAUTH_CLIENT_SECRET=zz7-wlKBIkfm_PE70jlZGzk7
  - OAUTH_TOKEN=1/3U9xkLMmmrLTjR0epvVO9zmxOrrvXpWPUIVdLfeGa-M
  - OAUTH_SECRET=zZT1qUyi5t-il01tvxP3QjzT
before_script:
  - psql -c 'create database victorykit_test;' -U postgres
  - bundle exec rake db:migrate
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"