language: ruby
rvm:
  - 1.9.3
services:
  - redis
before_script:
  - psql -c 'create database victorykit_test;' -U postgres
  - bundle exec rake db:migrate
  - "export ANALYTICS_ID=UA-33980823-1"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"